version: "3"
services:
  postgres:
    image: postgres:14.5
    container_name: yadiskapi-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: yadiskapi
      POSTGRES_USER: yadiskapi
      POSTGRES_PASSWORD: pass
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - yadiskapi-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  app:
    build: .
    image: yadiskapi-image
    container_name: yadiskapi
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      # https://docs.docker.com/compose/networking/
      DB_DSN: "postgresql+asyncpg://yadiskapi:pass@postgres/yadiskapi"
    ports:
      - "80:80"

volumes:
  yadiskapi-pgdata: {}