# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2022-09-09T09:33:36+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class SystemItemType(Enum):
    FILE = 'FILE'
    FOLDER = 'FOLDER'


class SystemItem(BaseModel):
    id: str = Field(..., description='Уникальный идентфикатор', example='элемент_1_1')
    url: Optional[str] = Field(
        None, description='Ссылка на файл. Для папок поле равнно null.'
    )
    date: datetime = Field(
        ...,
        description='Время последнего обновления элемента.',
        example='2022-05-28T21:12:01.000Z',
    )
    parentId: Optional[str] = Field(
        None, description='id родительской папки', example='элемент_1_1'
    )
    type: SystemItemType
    size: Optional[int] = Field(
        None, description='Целое число, для папки - это суммарный размер всех элеметов.'
    )
    children: Optional[List[SystemItem]] = Field(
        None, description='Список всех дочерних элементов. Для файлов поле равно null.'
    )


class SystemItemImport(BaseModel):
    id: str = Field(..., description='Уникальный идентфикатор', example='элемент_1_1')
    url: Optional[str] = Field(
        None, description='Ссылка на файл. Для папок поле равнно null.'
    )
    parentId: Optional[str] = Field(
        None, description='id родительской папки', example='элемент_1_1'
    )
    type: SystemItemType
    size: Optional[int] = Field(
        None, description='Целое число, для папок поле должно содержать null.'
    )


class SystemItemImportRequest(BaseModel):
    items: Optional[List[SystemItemImport]] = Field(
        None, description='Импортируемые элементы'
    )
    updateDate: Optional[datetime] = Field(
        None,
        description='Время обновления добавляемых элементов.',
        example='2022-05-28T21:12:01.000Z',
    )


class SystemItemHistoryUnit(BaseModel):
    id: str = Field(..., description='Уникальный идентфикатор', example='элемент_1_1')
    url: Optional[str] = Field(
        None, description='Ссылка на файл. Для папок поле равнно null.'
    )
    parentId: Optional[str] = Field(
        None, description='id родительской папки', example='элемент_1_1'
    )
    type: SystemItemType
    size: Optional[int] = Field(
        None,
        description='Целое число, для папки - это суммарный размер всех её элементов.',
    )
    date: datetime = Field(..., description='Время последнего обновления элемента.')


class SystemItemHistoryResponse(BaseModel):
    items: Optional[List[SystemItemHistoryUnit]] = Field(
        None, description='История в произвольном порядке.'
    )


class Error(BaseModel):
    code: int
    message: str
